### ISSUE TITLE
Unspecified pop order for binary operation

### ISSUE THREAD

**Issue by brain-damage** [PacktPublishing/CPP-Reactive-Programming#2]
https://github.com/PacktPublishing/CPP-Reactive-Programming/blob/9eb878cca167076ee621c8d9f2e53bf53859fa97/Chapter05/Source_Code/BookExprEval.cpp#L216

The compiler can evaluate operands and other subexpressions in any order, and may choose another order when the same expression is evaluated again.
There is no concept of left-to-right or right-to-left evaluation in C++. This is not to be confused with left-to-right and right-to-left associativity of operators: the expression a() + b() + c() is parsed as (a() + b()) + c() due to left-to-right associativity of operator+, but the function call to c may be evaluated first, last, or between a() or b() at run time.
https://en.cppreference.com/w/cpp/language/eval_order

**Comment by sutambe** [comment]
@brain-damage That's fair. The right code is
``
else if (s.op == OPERATOR::MINUS ) { auto top = stk.Pop(); stk.Push(top - stk.Pop());} 
``
