### ISSUE TITLE
Look_free_Queue not thread safety mulltil pop, push

### ISSUE THREAD

**Issue by TKNgu** [PacktPublishing/CPP-Reactive-Programming#4]
`//==================================================
// C++ Atomic types explained
// A lock-free single-producer single-consumer queue
//==================================================
#include <atomic>
#include <iostream>
#include <memory>
#include <thread>

template <typename T>
class Lock_free_Queue {
 private:
  struct Node {
    std::shared_ptr<T> my_data;
    Node* my_next_node;
    Node() : my_next_node(nullptr) {}
  };

  std::atomic<Node*> my_head_node;
  std::atomic<Node*> my_tail_node;

  Node* pop_head_node() {
    Node* const old_head_node = my_head_node.load();
    for (int index = 0; index < 10000; index++) {
    }
    if (old_head_node == my_tail_node.load()) {
      return nullptr;
    }
    my_head_node.store(old_head_node->my_next_node);
    return old_head_node;
  }

 public:
  Lock_free_Queue()
      : my_head_node(new Node), my_tail_node(my_head_node.load()) {}
  Lock_free_Queue(const Lock_free_Queue& other) = delete;
  Lock_free_Queue& operator=(const Lock_free_Queue& other) = delete;

  ~Lock_free_Queue() {
    while (Node* const old_head_node = my_head_node.load()) {
      my_head_node.store(old_head_node->my_next_node);
      delete old_head_node;
    }
  }

  std::shared_ptr<T> dequeue() {
    Node* old_head_node = pop_head_node();
    if (!old_head_node) {
      return std::shared_ptr<T>();
    }
    std::shared_ptr<T> const result(old_head_node->my_data);
    delete old_head_node;
    return result;
  }

  void enqueue(T new_value) {
    std::shared_ptr<T> new_data(std::make_shared<T>(new_value));
    Node* p = new Node;
    Node* const old_tail_node = my_tail_node.load();
    old_tail_node->my_data.swap(new_data);
    old_tail_node->my_next_node = p;
    my_tail_node.store(p);
  }
};

void push(Lock_free_Queue<int>* q) {
  for (int i = 0; i < 10; ++i) {
    std::cout << "pushing " << i << std::endl;
    q->enqueue(i);
  }
}

void pop(Lock_free_Queue<int>* q) {
  for (int i = 0; i < 5; ++i) {
    std::cout << "poping " << *q->dequeue() << std::endl;
  }
}

int main() {
  Lock_free_Queue<int> q;
  std::thread t1(push, &q);
  std::this_thread::sleep_for(std::chrono::milliseconds(1));
  std::thread t2(pop, &q);
  std::thread t3(pop, &q);
  t1.join();
  t2.join();
  t3.join();
}
`

**Comment by rajat-packt** [comment]
Hey @TKNgu, can you share some more details (page number, file link from github repo, error log) regarding the issue you are facing?

I can see you have shared a block of code, but can you also describe the error so we may share the same with the author for their review, if needed.

**Comment by TKNgu** [comment]
@rajat-packt : [CPP-Reactive-Programming](https://github.com/PacktPublishing/CPP-Reactive-Programming/blob/master/Chapter04/Source_Code/lock_free_queue.cpp)

**Comment by rajat-packt** [comment]
We have tried reaching out to the author, we'll update you once we get a reply.
